### ISSUE TITLE
catkin_make

### ISSUE THREAD

**Issue by yanghan1ros** [neufieldrobotics/spinnaker_sdk_camera_driver#103]
/home/a-y-x/spinnaker_ws/src/spinnaker_camera_driver/include/spinnaker_sdk_camera_driver/std_include.h:5:10: fatal error: Spinnaker.h: 没有那个文件或目录
 #include "Spinnaker.h"
          ^~~~~~~~~~~~~
In file included from /home/a-y-x/spinnaker_ws/src/spinnaker_camera_driver/include/spinnaker_sdk_camera_driver/capture.h:4:0,
                 from /home/a-y-x/spinnaker_ws/src/spinnaker_camera_driver/src/capture.cpp:1:
/home/a-y-x/spinnaker_ws/src/spinnaker_camera_driver/include/spinnaker_sdk_camera_driver/std_include.h:5:10: fatal error: Spinnaker.h: 没有那个文件或目录
 #include "Spinnaker.h"
          ^~~~~~~~~~~~~

**Comment by samsdolphin** [comment]
Yeah, I have the same error.

**Comment by shahvi** [comment]
Please fill out a full bug report.

**Comment by yanghan1ros** [comment]
> Yeah, I have the same error.

you should install the relevant driver.    SpinView_QT

**Comment by rgov** [comment]
I filed this properly here: #105.

**Comment by PushyamiKaveti** [comment]
closing this issue as it is being addressed in #105
