### ISSUE TITLE
 How to change the frequency of the camera?

### ISSUE THREAD

**Issue by helloworld202** [neufieldrobotics/spinnaker_sdk_camera_driver#119]
**System Description**
Camera Name and Model:Blackfly S BFS-U3-51S5C
Operating System: Ubuntu16.04
Spinnaker Version: 2.0.0.147
ROS Version:  kinetic

When I set the parameter fps=40, the frequency obtained in Spinview is 40 hz, but the frequency of topic /camera_array/cam0/image_raw is always around 17. I tried to expand the buffer on this topic, but it didn't work. Is there any good idea to solve this problem?

**Comment by shahvi** [comment]
A common problem is when you are using the camera in a dark area, it automatically adjusts the exposure time to get good images. You can try setting the exposure to a low fixed value to see if it helps.  Remember exposure values are in micro seconds.
