### ISSUE TITLE
triggering in GigE camera

### ISSUE THREAD

**Issue by vivekarvind** [neufieldrobotics/spinnaker_sdk_camera_driver#13]
Hello,

I'm working with a GigE camera (I'm using Flir Oryx) and I seem to have a strange error. After setting `trigger source` to `software`, the `pCam->GetNextImage( )` function waits forever. Has anybody faced this problem before and found a solution? Please let me know. Thanks in advance!

**Comment by vivekarvind** [comment]
Figured it out myself, the `TriggerSoftware` CmmandPtr gets executed only by the press of the `enter key`.

**Comment by angegu** [comment]
Hi, what was the solution for this?
