### ISSUE TITLE
First frame ID was not zero./Error: Spinnaker: GenIcam::OutofRangeException = Value = 1 must be equal or greater than 2 

### ISSUE THREAD

**Issue by Xulei-Zhai** [neufieldrobotics/spinnaker_sdk_camera_driver#138]
Last time,I have run this project on Ubuntu 20.04 , but i was failed. You suggested me to use the tested spinnaker  version. This time , I used the tested spinnaker version 2.2.0.48 on ubuntu18.04， and meet the probelems as flollows. Looking for your reply.
Thank you very much.
[subnet-wrong.txt](https://github.com/neufieldrobotics/spinnaker_sdk_camera_driver/files/6708820/subnet-wrong.txt)

**System Description**
Camera Name and Model:FLIR  & ZX-SF1220C
Operating System:Ubuntu 18.04
Spinnaker Version:2.2.0.48
ROS Version: 1.14.11

[FATAL] [1624533412.635966106]: Error: Spinnaker: Camera is on a wrong subnet. [-1015]
[ WARN] [1624533412.635987315]: Most likely cause for this error is if your camera can't support color and your are trying to set it to color mode
[FATAL] [1624533412.816388305]: Failed to load nodelet '/acquisition_node` of type `acquisition/Capture` to manager `vision_nodelet_manager'
terminate called after throwing an instance of 'Spinnaker::Exception'
  what():  Spinnaker: Could not stop acquisition. Access denied [-1005]
[vision_nodelet_manager-2] process has died [pid 3128, exit code -6, cmd /opt/ros/melodic/lib/nodelet/nodelet manager __name:=vision_nodelet_manager __log:=/home/good/.ros/log/ac6bb07e-d4dd-11eb-80e3-a40c66050bb4/vision_nodelet_manager-2.log].
log file: /home/good/.ros/log/ac6bb07e-d4dd-11eb-80e3-a40c66050bb4/vision_nodelet_manager-2*.log
[acquisition_node-3] process has died [pid 3129, exit code 255, cmd /opt/ros/melodic/lib/nodelet/nodelet load acquisition/Capture vision_nodelet_manager __name:=acquisition_node __log:=/home/good/.ros/log/ac6bb07e-d4dd-11eb-80e3-a40c66050bb4/acquisition_node-3.log].
log file: /home/good/.ros/log/ac6bb07e-d4dd-11eb-80e3-a40c66050bb4/acquisition_node-3*.log

**Comment by vik748** [comment]
@Xulei-Zhai are you able to run the camera with SpinView?

**Comment by Xulei-Zhai** [comment]
![Uploading PrintScreen.png…]()
![PrintScreen](https://user-images.githubusercontent.com/72127095/123388027-f4acaf80-d5ca-11eb-8514-3458fecf9bc0.jpg)

@vik748 
Thanks for your reply.
I didn't use spinview before you told me. I just opened spinview on the terminal, and the interface shows that an adapter is connected. But when I click the start device acquisition button, the terminal shows device not open. I do not have a detailed manual for spinview and still can't solve the device not open problem.

**Comment by Xulei-Zhai** [comment]
@vik748 
When I restart the computer and run the specified launch file. 
First, the terminal will report an error ("first frame ID was not zero!..."). 
![first_time](https://user-images.githubusercontent.com/72127095/123390598-aa78fd80-d5cd-11eb-8aa2-3d56a4197d03.jpg)

Then, when I run the project once again, the terminal will prompt the following error every time ("GenICam::OutOfRangeException=Value = 1 must be equal or greater than Min = 2...")
![Except for the first time](https://user-images.githubusercontent.com/72127095/123390706-c8def900-d5cd-11eb-9890-28b01342b765.jpg)

Looking forward for your reply. Thank you very much.

**Comment by vik748** [comment]
We can't really help till you are able to make this work with SpinView or Acquisition examples provided with the SDK. You can to connect with FLIR support for that.
Once you get your system to talk to the camera I can help debug issues with the ROS driver.

**Comment by Xulei-Zhai** [comment]
It can now work on spinview, and I can video through spinview. However, when I run ROS driver, it still raises problems as shown in the above two pictures. We look forward to your reply.

**Comment by vik748** [comment]
Have you tried setting binning to 2 as suggested in the error message? You can set it in the `.launch` file.

**Comment by Xulei-Zhai** [comment]
yes，We have set it to 2 in the launch file, and there is a problem in the second picture.

**Comment by vik748** [comment]
Which version of spinnaker sdk and ROS are you using?

**Comment by Xulei-Zhai** [comment]
spinaker ：1.24.0.60
ros： melodic

**Comment by Xulei-Zhai** [comment]
I tried spinnaker version 2.2.0.48 before（i know it was tested on ubuntu18.04）, but there is still a problem

**Comment by vik748** [comment]
I would suggest sticking to 2.2.0.48 for melodic since I know that combination works. Unfortunately I have not ever seen or used the camera that you are using, so not sure what to say.  
All I can suggest is that you try to look at the parameters in SpinView and try to set them to the settings we are using in the ROS driver - https://github.com/neufieldrobotics/spinnaker_sdk_camera_driver/blob/9c9633038c17d06f4ba11da9a97dddeb59c0d72a/src/capture.cpp#L672

Hopefully that can help you identify which configuration is causing the issue.

**Comment by Xulei-Zhai** [comment]
Thank you very much. 
![2021-09-03 14-55-47 的屏幕截图](https://user-images.githubusercontent.com/72127095/131965972-a8c52f7e-8d97-4045-9577-45115719bd15.png)
![2021-09-03 14-56-10 的屏幕截图](https://user-images.githubusercontent.com/72127095/131965978-108e4468-c581-4144-bf46-83deb0cf518a.png)
![2021-09-03 14-56-32 的屏幕截图](https://user-images.githubusercontent.com/72127095/131965979-4357476c-1839-4a42-af98-d7152e304ffd.png)
![2021-09-03 14-57-50 的屏幕截图](https://user-images.githubusercontent.com/72127095/131965981-5ee4c55c-23cb-4bf3-b891-56a72b8c57a1.png)
![2021-09-03 14-58-31 的屏幕截图](https://user-images.githubusercontent.com/72127095/131965983-a3e6020a-2cc8-448e-b052-dc19416df4d0.png)
I have just successfully run this package, which mainly includes two steps. The first step is to change the value of bining in the corresponding launch file to 2. The second step is to comment out the code in line 59 mentioned in the error message. Then it runs successfully.

As shown in the figure above, thank you again for your help.
