### ISSUE TITLE
Fix the '' terminate called after throwing an instance of 'std::bad_cast' " error on exit.

### ISSUE THREAD

**Issue by shahvi** [neufieldrobotics/spinnaker_sdk_camera_driver#15]

**Comment by 4artit** [comment]
when will this bug be fixed? I am trying to use 4 cams using hardware trigger but I usually see this error.

**Comment by shahvi** [comment]
This bug doesnt seem to affect functionality so its not high priority. Are you able to use the 4 cameras together?

**Comment by 4artit** [comment]
I could not say I can do that. Sometimes It works but I should try several times before. I am using official hardware trigger circuit. 4 cams can not initialize at once.

**Comment by shahvi** [comment]
Can you paste the output so we can look at it.

**Comment by 4artit** [comment]
One is when it works well and the other is not.
![00](https://user-images.githubusercontent.com/12016607/53784895-0c734c00-3f5a-11e9-94c9-2b0a65ab21c3.png)
![01](https://user-images.githubusercontent.com/12016607/53784901-0da47900-3f5a-11e9-8771-525fc5ca674e.png)

**Comment by shahvi** [comment]
This could he related to cameras not getting enough power. How are you powering them? Just plugging into IUB ports or powered USB hub or external power?

**Comment by 4artit** [comment]
I connected master(primary) camera directly into computer and the others are connected to USB hub(this one do not have external power). I ordered powered usb hub. So when after I get that usb hub, I will test again.
Thanks for your help. I will upload that result too.

**Comment by 4artit** [comment]
When I use powered usb hub, another error is occurred.
![01](https://user-images.githubusercontent.com/12016607/53924929-67738300-40c1-11e9-92f9-caf719987649.png)

**Comment by shahvi** [comment]
Not a lot of information to go by there. Have you increased your USB buffer as suggested during installation.

**Comment by 4artit** [comment]
Thanks it fixed! previously I set use buffer as 1000 but now I increase 1500. It works very well.
I followed this instruction.
[https://importgeek.wordpress.com/2017/02/26/increase-usbfs-memory-limit-in-ubuntu/](https://importgeek.wordpress.com/2017/02/26/increase-usbfs-memory-limit-in-ubuntu/)
