### ISSUE TITLE
Unable to set BinningHorizontal to 1 (ptr retrieval).

### ISSUE THREAD

**Issue by MohamedNaveed** [neufieldrobotics/spinnaker_sdk_camera_driver#19]
I installed the package as per the procedure given in the Readme. But while running the launch file, I get this error. I use a CM3-U3-13S2M-CS camera.

Unable to set BinningHorizontal to 1 (ptr retrieval). Aborting...
[FATAL] [1548385968.642554237]: Error: Spinnaker: GenICam::AccessException= Node is not writable. : AccessException thrown in node 'BinningHorizontal' while calling 'BinningHorizontal.SetValue()' (file 'IntegerT.h', line 77) [-2006]

[ WARN] [1548385968.642580159]: Most likely cause for this error is if your camera can't support color and your are trying to set it to color mode
terminate called after throwing an instance of 'Spinnaker::Exception'
  what():  Spinnaker: GenICam::AccessException= Node is not writable. : AccessException thrown in node 'TriggerSoftware' while calling 'TriggerSoftware.Execute()' (file 'CommandT.h', line 61) [-2006]
[acquisition_node-2] process has died [pid 13535, exit code -6, cmd /home/naveed/Documents/forklift_ws/devel/lib/spinnaker_sdk_camera_driver/acquisition_node __name:=acquisition_node __log:=/home/naveed/.ros/log/163e809e-204f-11e9-b8aa-48e244c47c43/acquisition_node-2.log].
log file: /home/naveed/.ros/log/163e809e-204f-11e9-b8aa-48e244c47c43/acquisition_node-2*.log

**Comment by MohamedNaveed** [comment]
> I can't seem to find that model number on the web. What kind of camera is it?
> 
> Also have you set color to 0 as the error suggests?

The camera falls under the family Chameleon 3. (Model number edit: CM3-U3-13S2M-CS)

Yes, I set the default value of color to "false".

**Comment by shahvi** [comment]
@MohamedNaveed did the above suggestion help?

**Comment by MohamedNaveed** [comment]
> @MohamedNaveed did the above suggestion help?

Yes. After commenting the 2 lines you mentioned, the package works. I'm able to visualize through rqt_image_view. 

Thanks for your help.
