### ISSUE TITLE
camera_info & camera/set_camera_info

### ISSUE THREAD

**Issue by picatostas** [neufieldrobotics/spinnaker_sdk_camera_driver#26]
Is there any plans to implement these things ?
When listing topics, I can see that Camera_info has been initialized but doesnt show any info when using rostopic echo

**Comment by vik748** [comment]
You will need to specify the camera matrix and distortion coefficients.  You can add that to the config file and it will be published.

**Comment by picatostas** [comment]
Hi,
I was asking this because I wanted to use http://wiki.ros.org/camera_calibration for calibrating the camera but when running it, the service set_camera_info was not detected. In the end I did it "manually". Once I have the camera matrix & distortion coeficients where should I put them in the config file ?

**Comment by vik748** [comment]
Checkout the multicam_example at https://github.com/neufieldrobotics/spinnaker_sdk_camera_driver/blob/fd3d35e43ad590c4ef42937083317c56d5459386/params/multi-cam_example.yaml#L26
