### ISSUE TITLE
Inconsistency between README.md instructions for running the driver and the package name.

### ISSUE THREAD

**Issue by sulekahraman** [neufieldrobotics/spinnaker_sdk_camera_driver#28]
The package name in package.xml is "spinnaker_**sdk**_camera_driver" whereas the README.md instructions use package name "spinnaker_camera_driver."
I think either the instructions should be changed to 
``roslaunch spinnaker_sdk_camera_driver acquisition.launch``

or line 3 of package.xml should be changed to 
``<name>spinnaker_camera_driver</name>``

**Comment by vik748** [comment]
Thanks for pointing this out, we will correct ReadME.

**Comment by Benefe** [comment]
> Thanks for pointing this out, we will correct ReadME.

Did not happen yet
