### ISSUE TITLE
the topic contains no image, keeping initializing

### ISSUE THREAD

**Issue by weisongwen** [neufieldrobotics/spinnaker_sdk_camera_driver#4]
hi @shahvi , thanks for your kind effort,

i successfully install the spinnaker in ubuntu 16.06 using the https://www.ptgrey.com/support/downloads SDK.

However, after I launch the launch file. It keep initializing. The output of the terminal is shown as follows:

ROS_MASTER_URI=http://localhost:11311

process[acquisition_node-1]: started with pid [35983]
[ INFO] [1532634725.551832777]: [ OK ] USB memory: 1000 MB
20180726[ INFO] [1532634725.552007210]: *** PARAMETER SETTINGS ***
[ INFO] [1532634725.552042492]: ** Date = 20180726
[ INFO] [1532634725.553050693]:   Save path set via parameter to: /home/mscsim
[ INFO] [1532634725.553130185]:   Camera IDs:
[ INFO] [1532634725.554337614]:     18285435
[ INFO] [1532634725.555473278]:   Camera Aliases:
[ INFO] [1532634725.555527312]:     18285435 >> cam0
[ INFO] [1532634725.557665155]:   Unique time stamps for each camera: 0
[ INFO] [1532634725.558754244]:   color set to: 0
[ INFO] [1532634725.559858203]:   Exporting images to ROS: 1
[ INFO] [1532634725.560955787]:   Showing live images setting: 0
[ INFO] [1532634725.562036843]:   Showing grid-style live images setting: 0
[ INFO] [1532634725.563059372]:   Max Rate Save Mode: 0
[ INFO] [1532634725.564012400]:   Displaying timing details: 0
[ INFO] [1532634725.564774616]:   No. of images to skip set to: 20
[ INFO] [1532634725.565765973]:   Init sleep delays set to : 20 sec
[ WARN] [1532634725.566955677]:   'fps' Parameter not set, using default behavior: fps=20.00
[ INFO] [1532634725.567906886]:   'exp'=0, Setting autoexposure
[ INFO] [1532634725.568642868]:   Binning set to: 2
[ INFO] [1532634725.569545892]:   Using Software rate control, rate set to: 20
[ INFO] [1532634725.570253196]:   Saving images set to: 0
[ INFO] [1532634725.571615514]:   Camera coeffs not provided correctly, camera info messges will not be published.
[ INFO] [1532634725.571665739]: Creating system instance...
[ INFO] [1532634725.572125027]: Retreiving list of cameras...
[ INFO] [1532634727.607574562]: Numer of cameras found: 1
[ INFO] [1532634727.607647535]:  Cameras connected: 1
[ INFO] [1532634727.607699535]:   -18285435
[ INFO] [1532634727.612179084]: *** FLUSH SEQUENCE ***
[ INFO] [1532634727.612233628]: Initializing cameras...
[ INFO] [1532634728.067750532]: Deinitializing cameras...
[ INFO] [1532634728.072786168]: All cameras deinitialized.
[ INFO] [1532634728.072877135]: Initializing cameras...

**Comment by shahvi** [comment]
Good to hear.
