### ISSUE TITLE
Physical meaning of projection_coeff? 

### ISSUE THREAD

**Issue by yzhou377** [neufieldrobotics/spinnaker_sdk_camera_driver#47]
Greetings. I am wondering what is the physical meaning of projection_coeff? And how it is calculated? It feels like coming from intrinsic and distortion, but I am not sure how though... 

Please advise.. Thank you.

**Comment by shahvi** [comment]
We follow the message definition for sensor_msgs/CameraInfo - http://docs.ros.org/melodic/api/sensor_msgs/html/msg/CameraInfo.html

Hope that helps.
