### ISSUE TITLE
Unable to retrieve system instance. Aborting with error -1012

### ISSUE THREAD

**Issue by rgambardella66** [neufieldrobotics/spinnaker_sdk_camera_driver#58]
I have a windows console application written in C using visual studio 2013. the application reference all the needed Spinnaker libraries.
Within Visual Studio I can retrieve system instance and extract Frame from all cameras connected. The problem happens when i try to deploy the application via Installshield. The executable return the above error when calling the spinSystemGetInstance function.
Can someone help me on this matter?

**Comment by vik748** [comment]
This is the repo for a ROS driver on linux.  I think you need to get help from the folks at FLIR.
