### ISSUE TITLE
Hardware Trigger

### ISSUE THREAD

**Issue by yzhou377** [neufieldrobotics/spinnaker_sdk_camera_driver#68]
Hi community,

We are trying to use a hardware impulse (external) to trigger the camera for acquisition. However, I cannot find how to work on this. 

I have tried the acquisition mode, but it is not exactly working... Some help here?

Thanks in advance. 

Best,
Yiyang

**Comment by shahvi** [comment]
First thing would be to make sure that you can get it to work through SpinView.  If that works try using the code in external_trigger branch and set the external_trigger parameter to True.
